name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Inject server config
      run: |
        sed -i 's|rs-ny.rustdesk.com|103.40.14.14:33973|g' libs/hbb_common/src/config.rs
        sed -i 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|QXjGQibEKuQDg4QGfJpd1BPwJl4XcVoQO1B+KG+rBK0=|g' libs/hbb_common/src/config.rs

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.75
        targets: x86_64-pc-windows-msvc

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '120deac3062162151622ca4860575a33844ba10b'

    - name: Install vcpkg dependencies
      shell: bash
      run: |
        vcpkg install --triplet x64-windows-static

    - name: Build
      env:
        RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
      shell: bash
      run: |
        cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: winrar-windows-x64
        path: target/x86_64-pc-windows-msvc/release/winrar.exe
